---
- name: main
  hosts: localhost
  vars_files:
    - ./.credentials/keycred
  environment:
    AWS_ACCESS_KEY_ID: "{{ USER }}"
    AWS_SECRET_ACCESS_KEY: "{{ PASSWORD }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instance_type: "{{ INSTANCE_TYPE | default( 't2.micro' ) }}"
    instance_image: "{{ INSTANCE_IMAGE | default( 'ami-0f5457ab1b6214674' ) }}"
  tasks:
    - name: -- Firelink --
      import_role:
        name: Firelink
        tasks_from: create
      when: "'create' in status"

    - name: -- Firelink --
      import_role:
        name: Firelink
        tasks_from: destroy
      when: "'destroy' in status"

    - name: -- Firelink --
      import_role:
        name: Firelink
        tasks_from: start
      when: "'start' in status"

    - name: -- Firelink --
      import_role:
        name: Firelink
        tasks_from: stop
      when: "'stop' in status"