---
- name: Terminate instances
  ec2_instance:
    state: absent
    filters:
      instance-state-name: running
    region: us-east-2

- name: Delete Keypair
  ec2_key:
    name: automation
    state: 'absent'
    region: us-east-2

- name: Get EIP info
  ec2_eip_info:
    region: us-east-2
  register: result

- name: Release EIP
  ec2_eip:
    ip: "{{ result.addresses[0].public_ip }}"
    state: absent
    region: us-east-2