---
- name: Terminate instances
  ec2_instance:
    state: absent
    filters:
      key-name: automation
    region: us-east-2

- name: Delete Keypair
  ec2_key:
    name: automation
    state: 'absent'
    region: us-east-2