---
- name: Check Instances
  ec2_instance:
    filters:
      instance-state-name: stopped
    region: us-east-2
  ignore_errors: true
  register: result

- name: Run Instances
  ec2_instance:
    state: running
    filters:
      instance-state-name: stopped
    region: us-east-2
  when: result is succeeded